### ISSUE TITLE
Search: default sort order

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#391]
Programmes should be sorted alphabetically by their programme number
Projects should be sorted alphabetically by their project number
Organisations should be listed in the following order: FMO, NFPs, POs, DPPs, IOs, dpps

**Comment by andreeadima** [comment]
Work started on branch **default_sorting**.

Programmes and projects can be sorted easily, since their numbers are stored in a field named 'code'.

On the other hand, organisations are delicate. 

1. I guess NFP abbreviates National Focal Point, which is stored as a OrganisationRole. OrganisationRoles are stored as a standalone table and I have no way of making sure that I always have PO, NFP and so on. 
1. What I can try to do is try to see if I have that role (identifying it by it's complete role name?) and reorder organisations if they have that role. 
1. Organisations can have multiple roles - should I consider it for a role if I have that role in the organisation role list?

**Comment by andreeadima** [comment]
1. NFP, PO, DPP, PJDPP, PP, PJPT, PJPP, others

2. Consider highest ranking order.

**Comment by andreeadima** [comment]
@melish should this be closed?
