### ISSUE TITLE
Tooltip - http request for each flag when moving the mouse over the BS chart

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#62]

**Comment by mihai-macaneata** [comment]
I have tried caching the images using js to prevent new requests but it is impossible since caching can be only done in image() objects and the tooltip plugin does not support this type of object. 
I'm thinking of creating sprites and switching tooltip class on hover.
Another way would be converting flags to svg, but first I need to test if the tooltip plugin can generate svg objects.
If both methods fail, I'll use another tooltip library.

**Comment by melish** [comment]
The requests are served from the browser cache, so this is actually not important.
